[project]
name = "aoc-2023"
version = "0.0.12"
description = "Advent of Code 2023 solutions"
readme = "README.md"
requires-python = ">=3.13, <3.14"
authors = [
  { name = "Ferran Mirabent Rubinat", email = "ferran.miru@gmail.com" },
]
dependencies = []

[dependency-groups]
dev = ["pre-commit>=4.2.0", "ruff>=0.12.4", "ty>=0.0.1a15"]

[build-system]
requires = ["uv_build>=0.11.0,<1.0.0"]
build-backend = "uv_build"

[tool.uv]
add-bounds = "major"

[tool.uv.build-backend]
module-root = "src"
